# vmagent-1-service.yaml
apiVersion: v1
kind: Service
metadata:
  name: vmagent-1
  namespace: kube-vm
spec:
  selector:
    app: vmagent
    statefulset.kubernetes.io/pod-name: vmagent-1
  type: NodePort
  ports:
    - name: http
      port: 8429
      targetPort: http
---
# vmagent-1-vm-ingress.yaml
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: vmagent-1-vm
  namespace: kube-vm
spec:
  ingressClassName: nginx
  rules:
    - host: vmagent-1-vm.qikqiak.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: vmagent-1
                port:
                  number: 8429