# vmselect-vm-ingress.yaml
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: vmselect-vm
  namespace: kube-vm
spec:
  ingressClassName: nginx
  rules:
    - host: vmselect-vm.qikqiak.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: vmselect
                port:
                  number: 8481