# ci/simple-values.yaml
service:
  type: NodePort
  nodePort: 32001
rbac:
  pspEnabled: false
persistence:
  enabled: true
  storageClassName: nfs-csi # local-path # 指定 StorageClass
  accessModes:
    - ReadWriteOnce
  size: 1Gi