# vmagent-vmagent-demo-ingress.yaml
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: vmagent-vmagent-demo
  namespace: default
spec:
  ingressClassName: nginx
  rules:
    - host: vmagent-vmagent-demo.qikqiak.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: vmagent-vmagent-demo
                port:
                  number: 8429