# Ingress-vmalert-alertmanager.yaml
# alertmanager-ingress.yaml
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: alertmanager
  namespace: kube-vm
spec:
  ingressClassName: nginx
  rules:
    - host: alertmanager-vm.qikqiak.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: alertmanager
                port:
                  number: 9093
---
# vmalert-ingress.yaml
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: vmalert
  namespace: kube-vm
spec:
  ingressClassName: nginx
  rules:
    - host: vmalert.qikqiak.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: vmalert
                port:
                  number: 8080